### ISSUE TITLE
move configuration file from JSON to YAML

### ISSUE THREAD

**Issue by spMohanty** [geotagx/geotagx-project-template#12]
Hi,
Even if we developers are more comfortable with JSON files, most people who will use the project (atleast in its current CLI form) freak out when they see so much code-like stuff. I was wondering if we should move the JSON configuration file to YAML. Both JSON and YAML are easily interchangeable programatically, and the project configuration file will just be more readable. For example, the sample `project.json` in YAML looks like (converted using : `http://jsontoyaml.com/`) :

``` yaml

---
  name: "GeoTag-X Sample Project"
  short_name: "sample"
  description: "A sample GeoTag-X project."
  why: "This is a simple project that highlights GeoTag-X's features."
  questions: 
    - 
      id: 1
      title: "Can you see any water in the photo?"
      type: "binary"
      answer: 
        saved_as: "isWaterVisible"
      branch: 
        - 
          yes: 2
        - 
          no: "finish"
    - 
      id: 2
      title: "What color is the water?"
      type: "single_choice"
      answer: 
        saved_as: "waterColor"
        choices: 
          - 
            Red: "Red"
          - 
            AquaBlue: "Aqua Blue"
          - 
            Green: "Green"
          - 
            Orange: "Orange"
          - 
            Other: "Other"
    - 
      id: 3
      title: "Can you see small pools of water?"
      type: "binary"
      answer: 
        saved_as: "smallPoolsOfWaterVisible"
      branch: 
        - 
          no: 5
    - 
      id: 4
      title: "Are these small pools of water near human shelters or a settlement?"
      type: "binary"
      answer: 
        saved_as: "smallPoolsOfWaterNearShelters"
      branch: 8
    - 
      id: 5
      title: "Can you see a large body of water?"
      type: "binary"
      answer: 
        saved_as: "largeBodyOfWaterVisible"
      branch: 
        - 
          no: 7
    - 
      id: 6
      title: "Can you see any signs of fast moving water?"
      type: "multiple_choice"
      answer: 
        saved_as: "signsOfFastMovingWater"
        choices: 
          - 
            Peaks: "White peaks in the water"
          - 
            Rough: "Rough water surface"
          - 
            Swirling: "Water swirling around objects"
    - 
      id: 7
      title: "Can you see any of the following flood protection measures?"
      type: "multiple_choice"
      answer: 
        saved_as: "floodProtectionVisible"
        choices: 
          - 
            Sandbags: "Sandbags"
          - 
            Barriers: "Makeshift barriers"
          - 
            Embankments: "Embankments"
          - 
            Other: "Other"
    - 
      id: 8
      title: "Can you see any sources of drinking water?"
      type: "binary"
      answer: 
        saved_as: "sourcesOfDrinkingWaterVisible"
      branch: 
        - 
          no: 11
    - 
      id: 9
      title: "Which sources of drinking water can you see?"
      type: "multiple_choice"
      answer: 
        saved_as: "sourcesOfDrinkingWater"
        choices: 
          - 
            Pipes: "Water pipes and access taps"
          - 
            Tankers: "Water tankers"
    - 
      id: 10
      title: "Have they been affected by the flood waters?"
      type: "binary"
      answer: 
        saved_as: "sourcesOfDrinkingWaterAffected"
    - 
      id: 11
      title: "Which animals do you see?"
      type: "illustrated_multiple_choice"
      answer: 
        saved_as: "animalsVisible"
        choices: 
          - 
            label: "Cattle"
            value: "Cattle"
            illustration: 
              image: "http://www.interservicos.com/media/uploads/3n.png"
              source: 
                name: "Interservicos"
                url: "http://www.interservicos.com/index.php/en/projectos/detail/306/"
            more_examples: "https://www.google.com/#q=cattle+africa"
          - 
            label: "Camel"
            value: "Camel"
            illustration: 
              image: "http://www.animalcorner.co.uk/wildlife/camels/graphics/cameldrom.jpg"
              source: 
                name: "Animal Corner"
                url: "http://www.animalcorner.co.uk/wildlife/camels/camel_dromedary.html"
            more_examples: "https://www.google.com/#q=camel"
          - 
            label: "Horse"
            value: "Horse"
            illustration: 
              image: "http://40.media.tumblr.com/cf2d20197662f0a7f92bab14eb172f5e/tumblr_muk62bEGmk1r34z06o1_1280.jpg"
              source: 
                name: "Our Africa Blog"
                url: "http://www.ourafricablog.com/post/63820121729/nomadamsterdam-somali-horses-having-fun-at"
            more_examples: "https://www.google.com/#q=horse"
          - 
            label: "Sheep"
            value: "Sheep"
            illustration: 
              image: "http://media-cache-ec0.pinimg.com/236x/cd/44/16/cd44162bd06893707689624f33314daf.jpg"
              source: 
                name: "colouredsheep.org.nz"
                url: "http://www.colouredsheep.org.nz/"
            more_examples: "https://www.google.com/#q=sheep+africa"
          - 
            label: "Donkey"
            value: "Donkey"
            illustration: 
              image: "http://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Innocence_%283426318415%29.jpg/301px-Innocence_%283426318415%29.jpg"
              source: 
                name: "Innocence"
                url: "http://www.flickr.com/photos/adavey/3426318415/"
            more_examples: "https://www.google.com/#q=donkey"
          - 
            label: "Goat"
            value: "Goat"
            illustration: 
              image: "http://capda.org.au/wp-content/uploads/2013/10/DSC09840-960x640.jpg"
              source: 
                name: "CAPDA"
                url: "http://capda.org.au/goat-and-chicken-raising-projects/"
            more_examples: "https://www.google.com/#q=goat"
          - 
            label: "Oxen"
            value: "Oxen"
            illustration: 
              image: "http://markwatkinson.zenfolio.com/img/s3/v40/p357350409-3.jpg"
              source: 
                name: "Mark W. Atkinson"
                url: "http://markwatkinson.zenfolio.com/p709151464/h154CBC09#h154cbc09"
            more_examples: "https://www.google.com/#q=ox"
    - 
      id: 12
      title: "Can you geo-localize the photo?"
      type: "geotagging"
      answer: 
        saved_as: "geolocation"
```
